apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-workspaces
  namespace: organization-1
subjects:
  - kind: ServiceAccount
    name: krateo-lab-user
roleRef:
  kind: Role
  name: workspaces-reader
  apiGroup: rbac.authorization.k8s.io
