apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-lab
  namespace: organization-1
  labels:
    component: permission-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      component: permission-lab
  template:
    metadata:
      labels:
        component: permission-lab
    spec:
      serviceAccountName: krateo-lab-user
      containers:
        - name: permission-lab
          image: ghcr.io/krateoplatformops/permission-lab:0.3.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
