apiVersion: v1
kind: Service
metadata:
  name: permission-lab-svc
  namespace: organization-1
  labels:
    component: permission-lab
spec:
  selector:
    component: permission-lab
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
